### ISSUE TITLE
SQL Verification (OMOP Concepts): Measurement Concepts

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/OMOP2OBO#23]
**PURPOSE:** This query is designed to query the OMOP `measurement`, `concept`, `concept_synonym`, `concept_ancestor`, and `vocabulary` tables.

**QUERY TYPE:** `OMOP Concepts`
**RUNTIME:** `8.4` seconds   
**RESULTS:** `1,606` rows (i.e. unique CONCEPT_IDs) 

**TASK:** @mgkahn - Anything you think I should change or anything that needs improvement?

``` SQL
WITH 
  measurement_concepts
  AS (SELECT
        m.measurement_concept_id AS CONCEPT_ID,
        c.concept_code AS CONCEPT_SOURCE_CODE, 
        c.concept_name AS CONCEPT_LABEL,
        c.vocabulary_id AS CONCEPT_VOCAB,
        v.vocabulary_version AS CONCEPT_VOCAB_VERSION
      FROM 
        CHCO_DeID_Oct2018.measurement m 
        JOIN CHCO_DeID_Oct2018.concept c ON m.measurement_concept_id = c.concept_id
        JOIN CHCO_DeID_Oct2018.vocabulary v ON c.vocabulary_id = v.vocabulary_id
      WHERE 
        c.concept_name != "No matching concept" 
        AND c.domain_id = "Measurement"
      GROUP BY CONCEPT_ID, CONCEPT_SOURCE_CODE, CONCEPT_LABEL, CONCEPT_VOCAB, CONCEPT_VOCAB_VERSION),
  
  measurement_ancestors
  AS (SELECT
        ca.descendant_concept_id AS CONCEPT_ID,
        STRING_AGG(DISTINCT(CAST(c1.concept_id as STRING)), " | ") AS ANCESTOR_CONCEPT_ID,
        STRING_AGG(DISTINCT(c1.concept_code), " | ") AS ANCESTOR_SOURCE_CODE, 
        STRING_AGG(DISTINCT(c1.concept_name), " | ") AS ANCESTOR_LABEL,
        STRING_AGG(DISTINCT(c1.vocabulary_id), " | ") AS ANCESTOR_VOCAB,
        STRING_AGG(DISTINCT(v.vocabulary_version), " | ") AS ANCESTOR_VOCAB_VERSION
      FROM 
        CHCO_DeID_Oct2018.concept_ancestor ca
        JOIN CHCO_DeID_Oct2018.concept c1 ON ca.ancestor_concept_id = c1.concept_id
        JOIN CHCO_DeID_Oct2018.vocabulary v ON c1.vocabulary_id = v.vocabulary_id
      WHERE 
        ca.descendant_concept_id IN (SELECT CONCEPT_ID FROM measurement_concepts)
        AND c1.concept_name != "No matching concept"
        AND c1.concept_id IS NOT NULL
        AND c1.domain_id = "Measurement"
      GROUP BY CONCEPT_ID),
  
  measurement_results
  AS (SELECT 
        measurement_concept_id AS CONCEPT_ID,
        CASE WHEN REGEXP_CONTAINS(STRING_AGG(range_low_source_value, ""), r'(?i)(positive|negative)') IS TRUE THEN "Negative/Positive" 
             WHEN REGEXP_CONTAINS(STRING_AGG(range_high_source_value, ""), r'(?i)(positive|negative)') IS TRUE THEN "Negative/Positive"         
             WHEN REGEXP_CONTAINS(STRING_AGG(range_low_source_value, ""), r'[[:digit:]]') IS TRUE THEN "Normal/Low/High"
             WHEN REGEXP_CONTAINS(STRING_AGG(range_high_source_value, ""), r'[[:digit:]]') IS TRUE THEN "Normal/Low/High"
             ELSE NULL END AS RESULT_TYPE
      FROM CHCO_DeID_Oct2018.measurement
      WHERE measurement_concept_id in (SELECT CONCEPT_ID FROM measurement_concepts)
      GROUP BY CONCEPT_ID),
  
  measurement_scale
  AS (SELECT 
        s.concept_id AS CONCEPT_ID,
        STRING_AGG(DISTINCT(s.concept_synonym_name), " | ") AS CONCEPT_SYNONYM,
        STRING_AGG(s.concept_synonym_name, ""),
        CASE WHEN REGEXP_CONTAINS(STRING_AGG(s.concept_synonym_name, ""), r'(?i)ordinal') IS TRUE THEN "ORD"
             WHEN REGEXP_CONTAINS(STRING_AGG(s.concept_synonym_name, ""), r'(?i)nominal') IS TRUE THEN "NOM"
             WHEN REGEXP_CONTAINS(STRING_AGG(s.concept_synonym_name, ""), r'(?i)quantitative') IS TRUE THEN "QUANT"
             WHEN REGEXP_CONTAINS(STRING_AGG(s.concept_synonym_name, ""), r'(?i)qualitative') IS TRUE THEN "QUAL"
             WHEN REGEXP_CONTAINS(STRING_AGG(s.concept_synonym_name, ""), r'(?i)narrative') IS TRUE THEN "NAR"
             WHEN REGEXP_CONTAINS(STRING_AGG(s.concept_synonym_name, ""), r'(?i)doc') IS TRUE THEN "DOC"
             WHEN REGEXP_CONTAINS(STRING_AGG(s.concept_synonym_name, ""), r'(?i)(panel|pnl|panl)') IS TRUE THEN "PNL"
             ELSE "Unmapped Scale Type" END AS SCALE
        FROM CHCO_DeID_Oct2018.concept_synonym s 
        WHERE s.concept_id in (SELECT CONCEPT_ID FROM measurement_concepts)
        GROUP BY CONCEPT_ID),
  
  measurement_metadata_update
  AS (SELECT
        r.CONCEPT_ID,
        CASE WHEN (r.RESULT_TYPE IS NULL AND s.SCALE = "ORD") AND REGEXP_CONTAINS(s.CONCEPT_SYNONYM, r'(?i)screen') IS TRUE THEN "Negative/Positive"
             WHEN (r.RESULT_TYPE IS NULL AND s.SCALE = "ORD") AND REGEXP_CONTAINS(s.CONCEPT_SYNONYM, r'(?i)presence') IS TRUE THEN "Negative/Positive"
             WHEN r.RESULT_TYPE IS NULL AND s.SCALE = "QUANT" THEN "Normal/Low/High"
             WHEN r.RESULT_TYPE IS NOT NULL THEN r.RESULT_TYPE
             ELSE "Unknown Result Type" END AS RESULT_TYPE,
        CASE WHEN s.SCALE IS NULL THEN "Other"  # for non-LOINC scale types
             ELSE s.SCALE END AS SCALE
        FROM
          (SELECT * FROM measurement_results) r
          FULL JOIN (SELECT * FROM measurement_scale) s ON r.CONCEPT_ID = s.CONCEPT_ID)

SELECT
  m.CONCEPT_ID,
  m.CONCEPT_SOURCE_CODE,
  m.CONCEPT_LABEL,
  m.CONCEPT_VOCAB,
  m.CONCEPT_VOCAB_VERSION,
  s.CONCEPT_SYNONYM,
  a.ANCESTOR_CONCEPT_ID,
  a.ANCESTOR_SOURCE_CODE, 
  a.ANCESTOR_LABEL,
  a.ANCESTOR_VOCAB,
  a.ANCESTOR_VOCAB_VERSION,
  u.SCALE,
  u.RESULT_TYPE
  
FROM measurement_concepts m
  FULL JOIN measurement_ancestors a ON m.CONCEPT_ID = a.CONCEPT_ID
  FULL JOIN measurement_scale s ON m.CONCEPT_ID = s.CONCEPT_ID
  FULL JOIN measurement_metadata_update u ON m.CONCEPT_ID = u.CONCEPT_ID;
 ```

**Comment by mgkahn** [comment]
Some topics to discuss:

- What is happening with the GROUP BY clauses in your CTEs?
- While to tremendous performance advantage of using case insensitive regex is now gone, I personally still find it easier to use the case insensitive version so I never have to worry about including a lower() or upper() function ever. See https://medium.com/google-cloud/bigquery-performance-tips-searching-for-text-8x-faster-f9314927b8d2
- Some of your regex's are redundant. For example 'document|doc' -- the 'doc' pattern will match 'document'.
- I am assuming that you are asking sites to do this query also so you grab their version of the vocabulary and the state of its concept/concept ancestor table since the vocal tables change so often so could be different versions at different sites. Is this right? Else, you could just run the first CTE at the site and the ancestor stuff on a local (recent) copy of the vocab.
- Maybe consider left JOINs in the main query. There **should** be no difference but I wonder if there will be some measurements without a scale or range. But since you have a final clause in those CASE statements, I think you are OK. Just something to validate that row counts are not dropping.

**Comment by callahantiff** [comment]
This was VERY helpful, thank you! The updated query is shown above and reflects the changes discussed here as well as on the other, related issues.

> Some topics to discuss:
> 
> * What is happening with the GROUP BY clauses in your CTEs?

I am using a `GROUP BY` in the CTEs, rather than `DISTINCT` because I believe it's more performant and I wanted to make sure that I was removing duplicate concepts. Is there a better way to do this?  

> * While to tremendous performance advantage of using case insensitive regex is now gone, I personally still find it easier to use the case insensitive version so I never have to worry about including a lower() or upper() function ever. See https://medium.com/google-cloud/bigquery-performance-tips-searching-for-text-8x-faster-f9314927b8d2

Great suggestion! I have updated the query accordingly  

> * Some of your regex's are redundant. For example 'document|doc' -- the 'doc' pattern will match 'document'.

Good call. Redundancies have been removed  

> * I am assuming that you are asking sites to do this query also so you grab their version of the vocabulary and the state of its concept/concept ancestor table since the vocal tables change so often so could be different versions at different sites. Is this right? Else, you could just run the first CTE at the site and the ancestor stuff on a local (recent) copy of the vocab.

I added some code to get the vocabulary version for all concepts and ancestors so we will have that. this query is not being sent to other sites (just the coverage V1 or if we have to the V2) so we won't have to worry about the ancestor concepts, but thank you for bringing this to my attention because I think we will want to make sure that we mention this in the paper, should anyone want to run these scripts  

> * Maybe consider left JOINs in the main query. There **should** be no difference but I wonder if there will be some measurements without a scale or range. But since you have a final clause in those CASE statements, I think you are OK. Just something to validate that row counts are not dropping.  

I compared the output from both types of joins and don't see a difference. OK to keep it as shown above?

**Comment by callahantiff** [comment]
Query updated above per our conversation yesterday. Everything look OK to you?


For fun, I have included the updated `SCALE` and `RESULT_TYPE` counts below:

CONCEPT_VOCAB | SCALE | RESULT_TYPE | COUNT
-- | -- | -- | -- 
 LOINC | DOC | Unknown Result Type | 1  
 LOINC | NAR | Negative/Positive | 1   
LOINC | NAR | Normal/Low/High | 3  
LOINC | NAR | Unknown Result Type | 20 
LOINC | NOM | Negative/Positive | 4 
LOINC | NOM | Normal/Low/High | 4   
LOINC | NOM | Unknown Result Type | 58   
LOINC | ORD | Negative/Positive | 174   
LOINC | ORD | Normal/Low/High | 18   
LOINC | PNL | Normal/Low/High | 1   
LOINC | PNL | Unknown Result Type | 1   
LOINC | QUANT | Negative/Positive | 41   
LOINC | QUANT | Normal/Low/High | 1279   
PEDSnet | Other | Normal/Low/High | 1

**Comment by mgkahn** [comment]
So, Unknown Result type using heuristics: 20 (NAR) + 58 (NOM) + 1 (PNL). The 20 narrative makes sense. The 58 NOM makes it the largest group in NOM with only 8 NOMs being assigned a result_type. So it dominates the NOM class but the NOM class is small relative the the sum of all of the other classes. So I guess we go with this as "acceptable"

**Comment by callahantiff** [comment]
OK, query above updated to remove `standard_concept = "S"`. Good to go?

**Comment by callahantiff** [comment]
Good morning! @mgkahn - just circling back. Are you OK with this? Can I close this issue?

**Comment by mgkahn** [comment]
OK.

**Comment by callahantiff** [comment]
Great! Closing this now.
