### ISSUE TITLE
SQL Verification (OMOP Concepts): Condition_Occurrence Concepts

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/OMOP2OBO#24]
**PURPOSE:** This query is designed to query the OMOP `condition_occurrence`, `concept`, `concept_synonym`, `concept_ancestor`, and `vocabulary` tables.

**QUERY TYPE:** `OMOP Concepts`
**RUNTIME:** `20.5` seconds   
**RESULTS:** `29,129` rows (i.e. unique CONCEPT_IDs) 

**TASK:** @mgkahn - Anything you think I should change or anything that needs improvement?

```SQL
WITH 
  condition_concepts
  AS (SELECT
        c.condition_concept_id AS CONCEPT_ID,
        c1.concept_code AS CONCEPT_SOURCE_CODE, 
        c1.concept_name AS CONCEPT_LABEL,
        c1.vocabulary_id AS CONCEPT_VOCAB,
        v.vocabulary_version AS CONCEPT_VOCAB_VERSION
      FROM 
        CHCO_DeID_Oct2018.condition_occurrence c 
        JOIN CHCO_DeID_Oct2018.concept c1 ON c.condition_concept_id = c1.concept_id
        JOIN CHCO_DeID_Oct2018.vocabulary v ON c1.vocabulary_id = v.vocabulary_id
      WHERE 
        c1.concept_name != "No matching concept" 
        AND c1.domain_id = "Condition"
      GROUP BY CONCEPT_ID, CONCEPT_SOURCE_CODE, CONCEPT_LABEL, CONCEPT_VOCAB, CONCEPT_VOCAB_VERSION),
  
  condition_ancestors
  AS (SELECT
        ca.descendant_concept_id AS CONCEPT_ID,
        STRING_AGG(DISTINCT(CAST(c1.concept_id as STRING)), " | ") AS ANCESTOR_CONCEPT_ID,
        STRING_AGG(DISTINCT(c1.concept_code), " | ") AS ANCESTOR_SOURCE_CODE, 
        STRING_AGG(DISTINCT(c1.concept_name), " | ") AS ANCESTOR_LABEL,
        STRING_AGG(DISTINCT(c1.vocabulary_id), " | ") AS ANCESTOR_VOCAB,
        STRING_AGG(DISTINCT(v.vocabulary_version), " | ") AS ANCESTOR_VOCAB_VERSION
      FROM 
        CHCO_DeID_Oct2018.concept_ancestor ca
        JOIN CHCO_DeID_Oct2018.concept c1 ON ca.ancestor_concept_id = c1.concept_id
        JOIN CHCO_DeID_Oct2018.vocabulary v ON c1.vocabulary_id = v.vocabulary_id
      WHERE 
        ca.descendant_concept_id IN (SELECT CONCEPT_ID FROM condition_concepts)
        AND c1.concept_name != "No matching concept"
        AND c1.concept_id IS NOT NULL
        AND c1.domain_id = "Condition"
      GROUP BY CONCEPT_ID),
  
  condition_synonyms
  AS (SELECT 
        s.concept_id AS CONCEPT_ID,
        STRING_AGG(DISTINCT(s.concept_synonym_name), " | ") AS CONCEPT_SYNONYM
        FROM CHCO_DeID_Oct2018.concept_synonym s 
        WHERE s.concept_id in (SELECT CONCEPT_ID FROM condition_concepts)
        GROUP BY CONCEPT_ID)

SELECT
  c.CONCEPT_ID,
  c.CONCEPT_SOURCE_CODE,
  c.CONCEPT_LABEL,
  c.CONCEPT_VOCAB,
  c.CONCEPT_VOCAB_VERSION,
  s.CONCEPT_SYNONYM,
  a.ANCESTOR_CONCEPT_ID,
  a.ANCESTOR_SOURCE_CODE, 
  a.ANCESTOR_LABEL,
  a.ANCESTOR_VOCAB,
  a.ANCESTOR_VOCAB_VERSION
  
FROM condition_concepts c
  FULL JOIN condition_ancestors a ON c.CONCEPT_ID = a.CONCEPT_ID
  FULL JOIN condition_synonyms s ON c.CONCEPT_ID = s.CONCEPT_ID;
```

**Comment by mgkahn** [comment]
Does it matter to what you are doing that there are allowable (standard) CONDITION_OCCURRENCE concepts that are not pulled from the SNOMED vocabulary?

<img width="444" alt="image" src="https://user-images.githubusercontent.com/3923918/86371423-171d1e80-bc3e-11ea-8934-b8840c426346.png">

**Comment by mgkahn** [comment]
Same comment about looking at INNER JOIN counts versus LEFT JOIN counts in the final query. Every concept is supposed to have at least one ancestor (itself) so this should be fine. But since OMOP vocabularies have lots of issues, I would check. I won't write this again for the other queries.

**Comment by callahantiff** [comment]
> Same comment about looking at INNER JOIN counts versus LEFT JOIN counts in the final query. Every concept is supposed to have at least one ancestor (itself) so this should be fine. But since OMOP vocabularies have lots of issues, I would check. I won't write this again for the other queries.

There should not be, I set vocabulary_id to "SNOMED". I verified this in a prior query, no other vocabularies were coming through.

**Comment by callahantiff** [comment]
> Does it matter to what you are doing that there are allowable (standard) CONDITION_OCCURRENCE concepts that are not pulled from the SNOMED vocabulary?
> 
> <img alt="image" width="444" src="https://user-images.githubusercontent.com/3923918/86371423-171d1e80-bc3e-11ea-8934-b8840c426346.png">

There should not be, I set vocabulary_id to "SNOMED". I verified this in a prior query, no other vocabularies were coming through.

**Comment by mgkahn** [comment]
JOINs: Missing my point. LEFT JOINS not "regular" JOINS.
SNOMED: Missing my point. Yes, your query only examines SNOMED. Are you OK with that? There could be non-SNOMED codes as valid standard codes that you will not be pulling.

**Comment by callahantiff** [comment]
> JOINs: Missing my point. LEFT JOINS not "regular" JOINS.
> SNOMED: Missing my point. Yes, your query only examines SNOMED. Are you OK with that? There could be non-SNOMED codes as valid standard codes that you will not be pulling.

**VOCABULARY:** For the query above, when I remove `vocabulary_id = "SNOMED"` and add `standard_concept = "S"` I get the same number of concepts. Initially, we had discussed only doing SNOMED, but I am happy to change it to be more relaxed if you think that's a better solution. I only worry that we will find things at other shops we can't account for, but that may happen anyways.

**JOINS:** For the JOINS, I want to remove the Inner part, I don't need to require every concept to have an ancestor or synonym. It's just a bonus for the mapping if they do. I will update this for the rest of the queries.

**Comment by mgkahn** [comment]
INNER JOIN is identical to JOIN
There is no difference between the two.

**Comment by callahantiff** [comment]
> INNER JOIN is identical to JOIN
> There is no difference between the two.

Yes, sorry I meant FULL JOIN. Going to stop responding until more coffee is onboard 😄 .

**Comment by callahantiff** [comment]
OK, the query has been updated. As a reminder, this query is not one that is sent to other sites. It's one that we use to full the initial mapping set. Good to go?

**Comment by callahantiff** [comment]
OK, in reference to [`issue 26`](https://github.com/callahantiff/OMOP2OBO/issues/26#issuecomment-653593026), the query above updated to remove `standard_concept = "S"`. Good to go?

**Comment by callahantiff** [comment]
Good morning! @mgkahn - just circling back. Are you OK with this? Can I close this issue?

**Comment by mgkahn** [comment]
Yes. proceed.

**Comment by callahantiff** [comment]
Thanks! Closing this now.
