### ISSUE TITLE
SQL Verification (OMOP Concepts): Drug_Exposure Concepts

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/OMOP2OBO#25]
**PURPOSE:** This query is designed to query the OMOP `drug_exposure`, `concept`, `concept_synonym`, `concept_ancestor`, and `vocabulary` tables.

**QUERY TYPE:** `OMOP Concepts`
**RUNTIME:** `27.0` seconds   
**RESULTS:** `11,949` rows; `9,175` unique drugs and `1,697` unique ingredients

**TASK:** @mgkahn - Anything you think I should change or anything that needs improvement?

```SQL
WITH 
  drug_concepts
  AS (SELECT
        d.drug_concept_id AS CONCEPT_ID,
        c.concept_code AS CONCEPT_SOURCE_CODE, 
        c.concept_name AS CONCEPT_LABEL,
        c.vocabulary_id AS CONCEPT_VOCAB,
        v.vocabulary_version AS CONCEPT_VOCAB_VERSION
      FROM 
        CHCO_DeID_Oct2018.drug_exposure d 
        JOIN CHCO_DeID_Oct2018.concept c ON d.drug_concept_id = c.concept_id
        JOIN CHCO_DeID_Oct2018.vocabulary v ON c.vocabulary_id = v.vocabulary_id
      WHERE 
        c.concept_name != "No matching concept" 
        AND c.domain_id = "Drug"
      GROUP BY CONCEPT_ID, CONCEPT_SOURCE_CODE, CONCEPT_LABEL, CONCEPT_VOCAB, CONCEPT_VOCAB_VERSION),
  
  drug_ancestors
  AS (SELECT
        ca.descendant_concept_id AS CONCEPT_ID,
        STRING_AGG(DISTINCT(CAST(c1.concept_id as STRING)), " | ") AS ANCESTOR_CONCEPT_ID,
        STRING_AGG(DISTINCT(c1.concept_code), " | ") AS ANCESTOR_SOURCE_CODE, 
        STRING_AGG(DISTINCT(c1.concept_name), " | ") AS ANCESTOR_LABEL,
        STRING_AGG(DISTINCT(c1.vocabulary_id), " | ") AS ANCESTOR_VOCAB,
        STRING_AGG(DISTINCT(v.vocabulary_id), " | ") AS ANCESTOR_VOCAB_VERSION
      FROM 
        CHCO_DeID_Oct2018.concept_ancestor ca
        JOIN CHCO_DeID_Oct2018.concept c1 ON ca.ancestor_concept_id = c1.concept_id
        JOIN CHCO_DeID_Oct2018.vocabulary v ON c1.vocabulary_id = v.vocabulary_id
      WHERE 
        ca.descendant_concept_id IN (SELECT CONCEPT_ID FROM drug_concepts)
        AND c1.concept_name != "No matching concept"
        AND c1.concept_id IS NOT NULL
        AND c1.domain_id = "Drug"
      GROUP BY CONCEPT_ID),
  
  drug_synonyms
  AS (SELECT 
        s.concept_id AS CONCEPT_ID,
        STRING_AGG(DISTINCT(s.concept_synonym_name), " | ") AS CONCEPT_SYNONYM
        FROM CHCO_DeID_Oct2018.concept_synonym s 
        WHERE s.concept_id in (SELECT CONCEPT_ID FROM drug_concepts)
        GROUP BY CONCEPT_ID),
        
  ingredient_concepts
  AS (SELECT
        ca.descendant_concept_id AS CONCEPT_ID,
        c1.concept_id AS INGREDIENT_CONCEPT_ID,
        c1.concept_code AS INGREDIENT_SOURCE_CODE, 
        c1.concept_name AS INGREDIENT_LABEL,
        c1.vocabulary_id AS INGREDIENT_VOCAB,
        v.vocabulary_version AS INGREDIENT_VOCAB_VERSION
      FROM 
        CHCO_DeID_Oct2018.concept_ancestor ca
        JOIN CHCO_DeID_Oct2018.concept c1 ON ca.ancestor_concept_id = c1.concept_id
        JOIN CHCO_DeID_Oct2018.vocabulary v ON c1.vocabulary_id = v.vocabulary_id
      WHERE 
        ca.descendant_concept_id IN (SELECT CONCEPT_ID FROM drug_concepts)
        AND c1.concept_name != "No matching concept"
        AND c1.concept_id IS NOT NULL
        AND c1.domain_id = "Drug"
        AND c1.concept_class_id = "Ingredient"
      GROUP BY CONCEPT_ID, INGREDIENT_CONCEPT_ID, INGREDIENT_SOURCE_CODE, INGREDIENT_LABEL, INGREDIENT_VOCAB, INGREDIENT_VOCAB_VERSION),
  
  ingredient_ancestors
  AS (SELECT
        ca.descendant_concept_id AS CONCEPT_ID,
        STRING_AGG(DISTINCT(CAST(c1.concept_id as STRING)), " | ") AS INGRED_ANCESTOR_CONCEPT_ID,
        STRING_AGG(DISTINCT(c1.concept_code), " | ") AS INGRED_ANCESTOR_SOURCE_CODE, 
        STRING_AGG(DISTINCT(c1.concept_name), " | ") AS INGRED_ANCESTOR_LABEL,
        STRING_AGG(DISTINCT(c1.vocabulary_id), " | ") AS INGRED_ANCESTOR_VOCAB,
        STRING_AGG(DISTINCT(v.vocabulary_version), " | ") AS INGRED_ANCESTOR_VOCAB_VERSION
      FROM 
        CHCO_DeID_Oct2018.concept_ancestor ca
        JOIN CHCO_DeID_Oct2018.concept c1 ON ca.ancestor_concept_id = c1.concept_id
        JOIN CHCO_DeID_Oct2018.vocabulary v ON c1.vocabulary_id = v.vocabulary_id
      WHERE 
        ca.descendant_concept_id IN (SELECT CONCEPT_ID FROM ingredient_concepts)
        AND c1.concept_name != "No matching concept"
        AND c1.concept_id IS NOT NULL
        AND c1.domain_id = "Drug"
      GROUP BY CONCEPT_ID)

SELECT
  d.CONCEPT_ID,
  d.CONCEPT_SOURCE_CODE,
  d.CONCEPT_LABEL,
  d.CONCEPT_VOCAB,
  d.CONCEPT_VOCAB_VERSION,
  s.CONCEPT_SYNONYM,
  a.ANCESTOR_CONCEPT_ID,
  a.ANCESTOR_SOURCE_CODE, 
  a.ANCESTOR_LABEL,
  a.ANCESTOR_VOCAB,
  a.ANCESTOR_VOCAB_VERSION,
  i.INGREDIENT_CONCEPT_ID,
  i.INGREDIENT_SOURCE_CODE,
  i.INGREDIENT_LABEL,
  i.INGREDIENT_VOCAB,
  i.INGREDIENT_VOCAB_VERSION,
  a2.INGRED_ANCESTOR_CONCEPT_ID,
  a2.INGRED_ANCESTOR_SOURCE_CODE,
  a2.INGRED_ANCESTOR_LABEL,
  a2.INGRED_ANCESTOR_VOCAB,
  a2.INGRED_ANCESTOR_VOCAB_VERSION
  
FROM drug_concepts d
  FULL JOIN drug_ancestors a ON d.CONCEPT_ID = a.CONCEPT_ID
  FULL JOIN drug_synonyms s ON d.CONCEPT_ID = s.CONCEPT_ID
  FULL JOIN ingredient_concepts i ON d.CONCEPT_ID = i.CONCEPT_ID
  FULL JOIN ingredient_ancestors a2 ON i.CONCEPT_ID = a2.CONCEPT_ID;
```

**Comment by mgkahn** [comment]
In this query, I would **DEFINITELY** look at INNER/LEFT JOINS because of the drug_synonyms. Not all drugs will have synonyms so I think you will have drop outs. Also walk the "ATC" vocabulary, not the VA Class in ingredient_ancestors. There has been a ton of work done on the ATC hierarchy (thanks to Katy Trinkley). The VA Class hierarchy is no longer supported by the VA and it probably going to go away.

**Comment by callahantiff** [comment]
Query updated above - OK with this?

In order to get ATC codes for ingredient_ancestors, I needed to relax the `standard_concept = "S"` constraint. Are you OK with that? For all other queries, I removed the specification on a specific vocabulary and added the `standard_concept = "S"` constraint. Happy to do whatever you think is best.

**Comment by mgkahn** [comment]
Just left comment in other issue about considering removing standard_concept = 'S' at least in the initial query (before you start your queries using concept_ancestor. For concept_ancestor, I would keep standard_concept = 'S'

**Comment by mgkahn** [comment]
I just checked this on current vocab -- tons of concepts in concept_ancestor that are standard_concept = 'C' that I think you want to capture in your query in the concept_ancestor CTE. So I suggest removing standard_concept = 'S' in that CTE.

**Comment by mgkahn** [comment]
select ca.*, c1.standard_concept as c1_standard_concept, c2.standard_concept as c2_standard_concept
from `sandbox-omop.CHCO_DeID_Oct2018.concept_ancestor` ca join `sandbox-omop.CHCO_DeID_Oct2018.concept` c1 on ca.ancestor_concept_id = c1.concept_id 
     join `sandbox-omop.CHCO_DeID_Oct2018.concept` c2 on ca.descendant_concept_id = c2.concept_id
where c1.standard_concept <> 'S' or c2.standard_concept <> 'S';

**Comment by callahantiff** [comment]
Just to confirm, should I remove `standard_concept = "S"` or switch to the query snippet shown below, which you sent earlier today? I liked the idea of removing the logic all together and then having the ability to further filter on our end if need be. Adding a pointer to the other issue where you initially mentioned this ([`issue 26`](https://github.com/callahantiff/OMOP2OBO/issues/26#issuecomment-653593026)).  

Query updated above to reflect removing the `standard_concept = "S"` logic.

**Comment by callahantiff** [comment]
Good morning! @mgkahn - just circling back. Are you OK with this? Can I close this issue?

**Comment by mgkahn** [comment]
Remind me -- did we decide that we will be sending versions of this script (output from SQL Render) to the sites? At first we thought we would just run these pure terminology scripts on our own vocabulary. But then we discussed running on each site's vocabulary so we "saw" the hierarchy that they have in place (hence you adding vocab_version).

**Comment by callahantiff** [comment]
> Remind me -- did we decide that we will be sending versions of this script (output from SQL Render) to the sites? At first we thought we would just run these pure terminology scripts on our own vocabulary. But then we discussed running on each site's vocabulary so we "saw" the hierarchy that they have in place (hence you adding vocab_version).

I was going to offer to work with the first site to customize the queries, but I also built a Google Colab notebook ([here](https://gist.github.com/callahantiff/647ca7ee6acbde3860c5f71a5a21a1c4])), that they can use to run our query. I will paste in the query ahead of time and then all they will need to do is include their database and schema information as well as specify a relational database type. 

The query we will send them is Coverage v1 [here](#26 ), which is just a single query. Unless they don't want to send us any data, in which case we will send them the Coverage v2 queries (one for each clinical domain (n=`3`)).

**Comment by callahantiff** [comment]
Will close this for now since I think we are good. Please re-open if you disagree.
