### ISSUE TITLE
SQL Verification - OMOP Coverage V2

### ISSUE THREAD

**Issue by callahantiff** [callahantiff/OMOP2OBO#27]
**PURPOSE:** This query is designed to query an OMOP instance and return 2 columns. This query makes the assumption that the other shops cannot share detailed results and thus we calculate and return simple coverage statistics.
- `COVERED_CONCEPTS` -  The number of concepts covered by our mappings  
- `TOTAL_CONCEPTS` -  The total number of mapped concepts   
- `DOMAIN` - A string indicating the clinical domain each of the concept codes belong to    

**QUERY TYPE:** `OMOP Coverage V2`
**RUNTIME:** `36.4` seconds   
**RESULTS:** `3` rows (i.e. unique CONCEPT_IDs) 

**TASK:** @mgkahn - What do you think about this?

**QUERIES:**
- [`OMOPCoverage_V2_Conditions.sql`](https://gist.github.com/callahantiff/f108ff351f4cfeffd5818a98bbad402f/raw/e3a70e3751456481df1580a5c6e096692f11518e/OMOPCoverage_V2_Conditions.sql)  
- [`OMOPCoverage_V2_Measurements.sql`](https://gist.github.com/callahantiff/f108ff351f4cfeffd5818a98bbad402f/raw/e3a70e3751456481df1580a5c6e096692f11518e/OMOPCoverage_V2_Measurements.sql)  
- [`OMOPCoverage_V2_Medications.sql`](https://gist.github.com/callahantiff/f108ff351f4cfeffd5818a98bbad402f/raw/e3a70e3751456481df1580a5c6e096692f11518e/OMOPCoverage_V2_Medications.sql)  

**SQLRender Query Templates:**  
- [`OMOPCoverage_V2_Template_Conditions.txt`](https://gist.github.com/callahantiff/f108ff351f4cfeffd5818a98bbad402f/raw/e3a70e3751456481df1580a5c6e096692f11518e/OMOPCoverage_V2_Template_Conditions.txt)  
- [`OMOPCoverage_V2_Template_Measurement.txt`](https://gist.github.com/callahantiff/f108ff351f4cfeffd5818a98bbad402f/raw/e3a70e3751456481df1580a5c6e096692f11518e/OMOPCoverage_V2_Template_Measurements.txt)  
- [`OMOPCoverage_V2_Template_Medications.txt`](https://gist.github.com/callahantiff/f108ff351f4cfeffd5818a98bbad402f/raw/e3a70e3751456481df1580a5c6e096692f11518e/OMOPCoverage_V2_Template_Medications.txt)

**Comment by mgkahn** [comment]
I understand this query. The issue may be that it may (probably will) run into DBMS limitations. For example, I know that Oracle can only parse SQL that has so many characters  (I don't recall the max query size). I believe PG is the same. 
<img width="701" alt="image" src="https://user-images.githubusercontent.com/3923918/86374159-7a5c8000-bc41-11ea-98ad-fc9d366b6792.png">

**Comment by callahantiff** [comment]
Yeah, I was trying to figure that out yesterday too. I think we should try to push for the V1 coverage scripts wherever possible and reserve this on back-up if there are places that don't want to share concept information. Do you think that sounds reasonable?

**Comment by callahantiff** [comment]
I have updated the query to ensure it is consistent with the other changes that we made just incase we need to use it.

**Comment by callahantiff** [comment]
UPDATE - This query contains `360,891` characters.

I looked up the limits for the other query engines and found the following:
- **BigQuery:** No system limits on query size (but admins can limit individual users)  
- **SQL Server:** `65,536` * (Network packet size)   
- **PostgreSQL:** `2,147,483,648` characters

<br>

So, from these figures it looks like we might be OK? I'm not sure how to interpret the SQL Server limit. Do you agree or do you prefer that I split it into 3 queries?

**Comment by callahantiff** [comment]
The SQLRender template it done and seems to work fine, except it won't work for BigQuery. For some reason they have a setting where they return the translated query in lower case. BigQuery won't except the schema name if it is lower-cased. Just something to keep in mind. Luckily, for this query the Oracle translation will also work for BigQuery, since we are not passing a database name, so we are covered.

The script is [here](https://github.com/callahantiff/OMOP2OBO/blob/development/scripts/R/OMOP2OBO_SQLRender.R) if you want to try it out. To run it, replace the `<<url>>` on line 19 with [this](https://gist.githubusercontent.com/callahantiff/f108ff351f4cfeffd5818a98bbad402f/raw/2adace4cce8f3720c651582fd85746f9e8a18d3f/OMOPCoverage_V1_template.txt) URL.

**Comment by callahantiff** [comment]
Hold off on running this, I have an awesome idea...

**Comment by callahantiff** [comment]
OK, never mind, this is good to check 😄

**Comment by mgkahn** [comment]
**Regarding query size**: Unless I am missing something, the query is larger than the max size for SQL Server, which is likely to a very common DBMS used at OHDSI sites.
**Regarding SQL Render**: BigQuery is INFURIATINGLY case sensitive in project name (database), data set name (schema) and table names but not case-sensitive for column names. While PG can be case sensitive, there is a configuration parameter that makes it case insensitive. All other DBMSs are case insensitive by default. So we tend to always have issues because we have upper/mixed case names that we use. Going forward, we should always, always, alway only give lowercase names to these objects. This is why the lower case versions of the BG code from SQL Render fails in our environment.

**Comment by callahantiff** [comment]
> **Regarding query size**: Unless I am missing something, the query is larger than the max size for SQL Server, which is likely to a very common DBMS used at OHDSI sites.

I have updated the query to now be three separate queries. There are links above for the SQL query and query templates for each. 

> **Regarding SQL Render**: BigQuery is INFURIATINGLY case sensitive in project name (database), data set name (schema) and table names but not case-sensitive for column names. While PG can be case sensitive, there is a configuration parameter that makes it case insensitive. All other DBMSs are case insensitive by default. So we tend to always have issues because we have upper/mixed case names that we use. Going forward, we should always, always, alway only give lowercase names to these objects. This is why the lower case versions of the BG code from SQL Render fails in our environment.

That's good to know. I will keep that in mind for the future.

In case you want to explore the script, I have made it available as a Google Colab Notebook via GitHub Gist ([`here`](https://gist.github.com/callahantiff/647ca7ee6acbde3860c5f71a5a21a1c4)):  
- Click the "Open in Colab" button and it will open the notebook. From there, you should not physically need to download anything to run it, just uncomment the `install.packages` lines and then run each code chunk in turn    
- To run it on one of our templates, replace the `<<url>>` place holder with [this](https://gist.github.com/callahantiff/f108ff351f4cfeffd5818a98bbad402f/raw/e3a70e3751456481df1580a5c6e096692f11518e/OMOPCoverage_V1_Template.txt) URL

**Comment by callahantiff** [comment]
Good morning! @mgkahn - just circling back. Are you OK with this? Can I close this issue and reach out to our first contact to begin the coverage studies (I will prioritize the COverage V1 Query first (issue #26) and only use this one if we are asked)?

**Comment by mgkahn** [comment]
Yes. Proceed.

**Comment by callahantiff** [comment]
Thank you! Closing this now.
