### ISSUE TITLE
Wiki: Broken links on V1.0 release page

### ISSUE THREAD

**Issue by ablack3** [callahantiff/OMOP2OBO#49]
**Wiki Page:**
- https://github.com/callahantiff/OMOP2OBO/wiki/V1.0

**Suggestions:**
- "All data used for this release can e downloaded directly from Zenodo (here) [http://doi.org/10.5281/zenodo.4247939](http://doi.org/10.5281/zenodo.4247939) " -> DOI not found
- Zenodo.org links under [Ontologies](https://github.com/callahantiff/OMOP2OBO/wiki/V1.0#ontologies-) section point to "404: resource not found"

![image](https://user-images.githubusercontent.com/10227522/99822569-5d0d4d00-2b21-11eb-9e03-91fccaedcea4.png)

**Comment by callahantiff** [comment]
@ablack3 - Sorry for the confusion. The links won't resolve (purposefully) until I finish the validation on release `v1.0`. In the process of finishing the las task now. Will let you know as soon as it is ready! 😄
